const puppeteer = require('puppeteer-core')
;(async () => {
  const b = await puppeteer.launch({ executablePath: process.env.CHROME_PATH ?? '/usr/bin/google-chrome', args: ['--no-sandbox'] })
  const p = await b.newPage()
  await p.setViewport({ width: 360, height: 740 })
  await p.goto(process.env.E2E_URL ?? 'http://localhost:4173/math-1class-20', { waitUntil: 'networkidle0' })
  await p.evaluate(() => localStorage.clear())
  await p.reload({ waitUntil: 'networkidle0' })
  const check = (l, c, e='') => console.log((c?'OK  ':'FAIL'), l, e)
  const btns = await p.$$eval('button', els => els.filter(e => e.offsetParent !== null && e.getAttribute('type') === 'submit').map(e => e.textContent.trim()))
  check('visible tab has one ✓ submit button', btns.length === 1 && btns[0] === '✓', JSON.stringify(btns))
  await p.click('input')
  const q = await p.$eval('.question', e => e.textContent)
  const m = q.match(/^(\d+)([+-])(\d+)=?$/)
  const ans = m[2] === '+' ? +m[1] + +m[3] : +m[1] - +m[3]
  await p.type('input', String(ans))
  await p.click('button[type=submit]')
  const st = await p.$eval('.stats', e => e.textContent)
  check('answer works', st.includes('Правильных ответов: 1'), st)
  await p.reload({ waitUntil: 'networkidle0' })
  const st2 = await p.$eval('.stats', e => e.textContent)
  const hist = await p.$eval('.history summary', e => e.textContent)
  check('progress persists', st2.includes('Правильных ответов: 1') && hist === 'История (1)', st2 + ' ' + hist)
  const overflow = await p.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  check('no horizontal scroll', !overflow)
  await b.close()
})()
